apiVersion: apps/v1
kind: Deployment
metadata:
  name: pds-2022-2-04
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pds-2022-2-04
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pds-2022-2-04
    spec:
      containers:
      - name: db
        image: postgres:13-alpine
        ports:
        - name: default-port
          containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: pds
        - name: POSTGRES_PASSWORD
          value: "123456"
        - name: POSTGRES_DB
          value: pds
      - name: backend
        image: 716814888065.dkr.ecr.us-east-2.amazonaws.com/pds-2022-2-04:backend-main
        imagePullPolicy: Always
        ports:
        - name: http-port
          containerPort: 5000
        env:
        - name: PGUSER
          value: pds
        - name: PGPASSWORD
          value: "123456"
        - name: POSTGRES_DB
          value: pds
        - name: PGHOST
          value: localhost
        - name: PGPORT
          value: "5432"
        - name: DBDIALECT
          value: postgres
      - name: frontend
        image: 716814888065.dkr.ecr.us-east-2.amazonaws.com/pds-2022-2-04:frontend-main
        imagePullPolicy: Always
        ports:
        - name: http-port
          containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: pds-2022-2-04
  namespace: default
spec:
  selector:
    app.kubernetes.io/name: pds-2022-2-04
  ports:
  - port: 80
    targetPort: 80
  type: NodePort
